server:
  port: 9090

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:tcp://localhost/~/dev"
    username: "sa"
    password: "sa"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect


